services:
  - title: "KDD'25 Paper Reviewer Committee"
    description: "31st ACM SIGKDD Conference on Knowledge Discovery and Data Mining"
    date: "Aug. 2024"
    icon: "fas fa-file-alt"
    
  - title: "ES-FoMo-II'24 Poster Reviewer Committee"
    description: "2nd Workshop on Efficient Systems for Foundation Models"
    date: "June 2024"
    icon: "fas fa-clipboard-list"
    
  - title: "KDD'24 Paper Reviewer Committee"
    description: "30th ACM SIGKDD Conference on Knowledge Discovery and Data Mining"
    date: "Mar. 2024"
    icon: "fas fa-file-alt"
    
  - title: "KDD'23 Paper Reviewer Committee"
    description: "29th ACM SIGKDD Conference on Knowledge Discovery and Data Mining"
    date: "Apr. 2023"
    icon: "fas fa-file-alt"