# Reviewing and program-committee service, newest first.

services:
  - title: "ASPLOS'26 Summer Artifact Evaluation Committee"
    description: "ACM International Conference on Architectural Support for Programming Languages and Operating Systems"
    date: "Jan. 2026"

  - title: "ASPLOS'26 Spring Artifact Evaluation Committee"
    description: "ACM International Conference on Architectural Support for Programming Languages and Operating Systems"
    date: "Aug. 2025"

  - title: "KDD'25 Program Committee"
    description: "31st ACM SIGKDD Conference on Knowledge Discovery and Data Mining"
    date: "Aug. 2024"

  - title: "ES-FoMo-II'24 Poster Reviewer"
    description: "2nd Workshop on Efficient Systems for Foundation Models @ ICML"
    date: "Jun. 2024"

  - title: "KDD'24 Program Committee"
    description: "30th ACM SIGKDD Conference on Knowledge Discovery and Data Mining"
    date: "Mar. 2024"

  - title: "KDD'23 Program Committee"
    description: "29th ACM SIGKDD Conference on Knowledge Discovery and Data Mining"
    date: "Apr. 2023"
